language: android

jdk: oraclejdk7

android:
  components:
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.1

    # The SDK version used to compile your project
    - android-22

    # Additional components
#    - extra-google-google_play_services
#    - extra-google-m2repository
    - extra-android-m2repository
#    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
#    - sys-img-armeabi-v7a-android-19
#    - sys-img-x86-android-17
  licenses:
    - android-sdk-license-.+

before_install:
 - chmod +x gradlew

script: 'travis_retry ./gradlew clean build'